import "../pug/components/base-slider/swiper";
import "../pug/components/switcher/switcher";
import "../pug/components/scroll-up-btn/scroll-up-btn";
import "../pug/components/burger/burger";
import "./modules/modals";
import "../pug/components/modals/staff-preview-modal/staff-preview-modal";
import "../pug/components/modals/cost-modal/cost-modal";
import "./modules/mask";
import "./modules/form-submit";
